-- Auto-generated from schema-map-postgres.yaml (map@sha1:FAEA49A5D5F8FAAD9F850D0F430ED451C5C1D707)
-- engine: postgres
-- table:  device_fingerprints

CREATE TABLE IF NOT EXISTS device_fingerprints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NULL,
  fingerprint_hash BYTEA NOT NULL,
  attributes JSONB NULL,
  risk_score SMALLINT NULL,
  first_seen TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  last_seen  TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  last_ip_hash BYTEA NULL,
  last_ip_key_version VARCHAR(64) NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_device_fp UNIQUE (fingerprint_hash),
  CONSTRAINT chk_df_risk CHECK (risk_score IS NULL OR (risk_score BETWEEN 0 AND 100))
);
