-- Auto-generated from schema-map-postgres.psd1 (map@62c9c93)
-- engine: postgres
-- table:  device_fingerprints
CREATE TABLE IF NOT EXISTS device_fingerprints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NULL,
  fingerprint_hash BYTEA NOT NULL,
  attributes JSONB NULL,
  risk_score SMALLINT NULL,
  first_seen TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  last_seen  TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  last_ip_hash BYTEA NULL,
  last_ip_key_version VARCHAR(64) NULL,
  CONSTRAINT uq_device_fp UNIQUE (fingerprint_hash),
  CONSTRAINT chk_df_risk CHECK (risk_score IS NULL OR (risk_score BETWEEN 0 AND 100))
);
